---
- name: Creating chassis config
  template: src=mx_chassis.j2 dest={{ tmp_dir }}/mx_chassis.cfg

- name: Creating common MX base config
  template: src=mx_system.j2 dest={{ tmp_dir }}/mx_system.cfg

- name: Creating management interface
  template: src=management_interface.j2 dest={{ tmp_dir }}/management_interface.cfg
